name: Build and Release Electron App

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the backend
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up maven
        uses: s4u/maven-settings-action@v3.1.0 

      - name: Install backend dependencies (Java)
        run: |
          cd backend
          mvn clean compile
        
      # Build the frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Build the Electron app
      - name: Install Electron dependencies
        run: |
          cd electron
          npm install

      - name: Build Electron app
        run: |
          cd electron
          npm run build  # Ensure this command builds your Electron app (e.g., using electron-builder)

      - name: Bump version
        run: |
          cd electron
          # Bump version
          npm version minor -m "Bump version to %s"

      - name: Read package.json
        id: package-version
        uses: zvonimirsun/read-package-version-actions@v2
        with: 
          path: "./electron"

           
      - name: Commit new version
        run: |
          git pull
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add electron/package.json electron/package-lock.json
          git commit -m "Bump version to ${{ steps.package-version.outputs.version }}"
          git push origin dev
          
      - name: Set VERSION output
        run: echo "VERSION=${{ steps.package-version.outputs.version }}" >> $GITHUB_ENV
        id: version_output
        continue-on-error: true   
          
      # Upload the packaged Electron `.exe` as an artifact
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "MoshPe-v${{ steps.package-version.outputs.version }}"
          path: electron/dist/*.exe  # Adjust the path where your .exe is built
    outputs:
      version: ${{ steps.package-version.outputs.version }}
      
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git tag
        run: |
          echo "Tagging with version: v${{ needs.build.outputs.version }}"
          git tag "v${{ needs.build.outputs.version }}"
          git push origin "v${{ needs.build.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: "MoshPe-v${{ needs.build.outputs.version }}"  # Adjust based on your setup
   
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "MoshPe-v${{ needs.build.outputs.version }}"
          tag: "v${{ needs.build.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
